### ISSUE TITLE
Fix devtools:check() run time too long issue

### ISSUE THREAD

**Issue by jasonzhao0307** [compbiomed/animalcules#16]

**Comment by jasonzhao0307** [comment]
This is the output most related to this issue:
✔  checking examples (11h 30m 5.8s)
   Examples with CPU or elapsed time > 5s
                            user system   elapsed
   download_refseq       446.578 41.465 28160.349
   find_biomarker         68.008  4.521    14.061
   mk_subread_index       16.856  3.910  4071.676
   bam_reheader_R         12.498  4.498    54.994
   merge_bam_files        12.829  3.952  5686.170
   combined_header        12.587  4.090    52.811
   filter_unmapped_reads   8.556  3.041  3253.693
   animalcules_id          7.601  2.345    47.532
   align_target            7.579  2.293    47.511

**Comment by jasonzhao0307** [comment]
To fix: we could just add a \dontrun{}
e.g: 
#' @examples
#' \dontrun{
#' XXXXXX
#' }

**Comment by definitelysean** [comment]
@jasonzhao0307 Just poking my head in here to say taht you should favor *not* using dontrun if you can get away with it; the Bioconductor curators will give you a hard time about it. Another alternative is to include a very small dataset with your package for which the different steps will run very quickly.

**Comment by jasonzhao0307** [comment]
@definitelysean Saved my day!! Thank you Sean :)

**Comment by wevanjohnson** [comment]
Note, this is probably my example and I will be making it better soon. Let’s talk next time I am in, there probably is a way to make these examples less complex.
