### ISSUE TITLE
add detail explanation for each button/option in the screen shot

### ISSUE THREAD

**Issue by jasonzhao0307** [compbiomed/animalcules#34]

**Comment by jasonzhao0307** [comment]
Also, add estimated running time for each function in the docs

**Comment by jasonzhao0307** [comment]
Try finish the docs improvement by Monday and submit to bioconductor

**Comment by wevanjohnson** [comment]
When is the bioconductor deadline for the next release?

**Comment by anfederico** [comment]
Submission deadline is April 5th and acceptance deadline is April 24th.
