### ISSUE TITLE
linux check error related to Entrez

### ISSUE THREAD

**Issue by jasonzhao0307** [compbiomed/animalcules#37]
Running examples in animalcules-Ex.R failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: find_taxonomy
> ### Title: Find the taxonomy for unlimited tids
> ### Aliases: find_taxonomy
> 
> ### ** Examples
> 
> taxonLevels <- find_taxonomy(tids=1200)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Error in the HTTP2 framing layer
Calls: find_taxonomy ... request_fetch -> request_fetch.write_memory -> <Anonymous>

ref:
https://github.com/ropensci/rentrez/issues/127

**Comment by jasonzhao0307** [comment]
https://github.com/ropensci/rentrez/issues/127 seems useful

**Comment by jasonzhao0307** [comment]
not sure if this will affect speed, will probably change back later.

**Comment by dwinter** [comment]
Hi @jasonzhao0307 , in case this is still relevant, the latest version of rentrez (v.1.2.2 on CRAN now) has addressed the bug that was throwing these errors
