### ISSUE TITLE
Import from phyloseq?

### ISSUE THREAD

**Issue by cjfields** [compbiomed/animalcules#38]
Just a quick question on whether importing data from phyloseq instances is a possibility.

**Comment by jasonzhao0307** [comment]
We currently don't have functions taking phyloseq objects into animalcules directly, but you could extract the count matrix and taxonomy table from phyloseq and upload to animalcules using the "count file" option

**Comment by jasonzhao0307** [comment]
@cjfields will work on writing a wrapper function to do that. will update here.

**Comment by jasonzhao0307** [comment]
Now animalcules support BIOM data input, so phyloseq users could firstly get BIOM from phyloseq object, and then upload BIOM to animalcules. Note that, the BIOM file must contain sample metadata information, if not, please add metadata info to the BIOM file via: http://biom-format.org/documentation/adding_metadata.html

**Comment by jasonzhao0307** [comment]
We added a section in the Data Upload tutorial on how to import phyloseq object: https://compbiomed.github.io/animalcules-docs/articles/rmd/upload.html
