### ISSUE TITLE
Biomarker names cannot handle spaces

### ISSUE THREAD

**Issue by Zinthrow** [compbiomed/animalcules#39]
Biomarker page cannot handle genus and species names that are two names such as unclassifed genus such as "unclassified Veilonellaceae". Not a huge issue and can be handle beforehand with adding an "_" in place of the spaces, but it might help to automatically replace these characters or add a warning telling users to make this change beforehand to the taxonomy file.

Thanks,
Alex

**Comment by anfederico** [comment]
Thanks for posting the issue, will look into this.

**Comment by jasonzhao0307** [comment]
Already fixed in the newest commit. Thank you! @Zinthrow
