### ISSUE TITLE
Counts file - only relative abundance data

### ISSUE THREAD

**Issue by davitero** [compbiomed/animalcules#43]
Hello,
My data are only OTUs and their relative abundances because they were obtained in a previous investigation.

So I was wondering, can I work with my relative abundance data instead of read counts?  That is, can I use this information as count file?

**Comment by wevanjohnson** [comment]
Yes, you can, multiple, your abundances by a large number, say 100000 and then round to the nearest integer, and treat them as counts. You can use any of the functions that use relative abundance just fine. But be careful with anything that uses the counts directly, e.g. DESeq2 on these data.

**Comment by davitero** [comment]
Dear Evan,
Thank you for your answer.  I will do as you say.
Best,
Dave
