### ISSUE TITLE
Is Alpha rarefaction required? 

### ISSUE THREAD

**Issue by s6aamani** [compbiomed/animalcules#46]
Hi,
       I have experienced that in diversity analysis done using qiime2, a rarefaction [normalization] step was recommended. However, in animalcules, no such step is performed. I am confused about whether rarefaction step is required or not. Will it change my result? 
Thank you

**Comment by jasonzhao0307** [comment]
The rarefaction step is not necessary. Check out this paper - McMurdie, P. J., and Holmes, S. (2014). Waste not, want not: why rarefying microbiome data is inadmissible. PLoS Comput. Biol. 10:e1003531. doi: 10.1371/journal.pcbi.1003531
