### ISSUE TITLE
lazy-load database ... PathoStat.rdb is corrupt

### ISSUE THREAD

**Issue by ReneKat** [compbiomed/animalcules#50]
Hello animalcules developers,
I'm excited to try out your tool but am having issues installing. I'm on a Mac OSX following installation instructions [here](https://bioconductor.org/packages/release/bioc/vignettes/animalcules/inst/doc/animalcules.html#run-shiny-app). 

Here's the exact error I'm receiving:

> Error in FUN(X[[i]], ...) : 
>   lazy-load database '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/PathoStat/R/PathoStat.rdb' is corrupt

I've deleted that file and had it recreated with no avail. 

Thanks for your help! 
Rene

**Comment by jasonzhao0307** [comment]
did you encounter this error during installation or after run run_animalcules() ?

**Comment by ReneKat** [comment]
Hi @jasonzhao0307 and thanks for the quick response. 
I receive the error when I go to load the animalcules library:
library(animalcules)

I have attached the Console here. Please let me know if you need more information.

[animalcules_error.txt](https://github.com/compbiomed/animalcules/files/9727833/animalcules_error.txt)

**Comment by jasonzhao0307** [comment]
Hey Rene,

I feel this is not a animalcules issue, cuz PathoStat.rdb is not required in animalcules, which makes wonder if you have tried to install PathoStat before? Later you might have deleted it and R is complaining about it. Try reinstall R?
